serverFiles:
  prometheus.yml:
    scrape_configs:
      - job_name: 'flask-app'
        static_configs:
          - targets: ['flask-demo-flask-service:5000']
        metrics_path: /metrics
        scrape_interval: 5s